site_name: Layout Docs
extra_css: [css/extra.css]
theme:
    name: material
    palette:
        scheme: slate
markdown_extensions:
    - admonition
    - toc: # https://python-markdown.github.io/extensions/toc/
          permalink: True
          toc_depth: 4
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - pymdownx.superfences

nav:
    - Home: index.md
    - Creating Custom Layouts:
          - Introduction: guide/index.md
          - Menu Files: guide/menu-files.md
          - Filetypes: guide/filetypes.md
          - Layouts: guide/layouts.md
          - Animations: guide/animations.md
          - Examples:
                Getting Started: guide/examples/index.md
                Changing Component Sizes: guide/examples/changing-component-sizes.md
                Repositioning the Gamerow: guide/examples/reposition-gamerow.md
                Stationary Game Icons: guide/examples/stationary-game-icons.md
                Custom Element Colours: guide/examples/custom-element-colours.md
    - Menu Documentation:
          - Introduction: menu-docs/index.md
          - List of Parts: menu-docs/list-of-parts.md
          - Menus:
                - Home Menu: menu-docs/menus/ResidentMenu
    - Definitions: definitions.md
    - Extras:
          - Guides: extras/guides.md
          - Tools: extras/tools.md
          - Discord Servers: extras/discord-servers.md
